// Copies IBM Plex woff2 files out of the @fontsource packages and generates the
// @font-face stylesheet.
//
// The fonts are self hosted rather than pulled from Google Fonts. The API runs
// under a strict CSP (`style-src 'self'`, `font-src 'self'`), so a remote font
// stylesheet is blocked outright and the page silently falls back to system
// faces. Weakening the CSP to allow fonts.googleapis.com would trade a
// security header for a webfont, and add a third party to the render path of a
// tool that otherwise has no external runtime dependencies.
//
// @fontsource packages are dev dependencies. The woff2 files are copied into
// public/fonts at build time and are not committed.

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outDir = path.join(ROOT, "public", "fonts");

const FAMILIES = [
  { package: "@fontsource/ibm-plex-sans", slug: "ibm-plex-sans", family: "IBM Plex Sans", weights: [400, 500, 600, 700] },
  { package: "@fontsource/ibm-plex-mono", slug: "ibm-plex-mono", family: "IBM Plex Mono", weights: [400, 500, 600] }
];

async function main() {
  await fs.rm(outDir, { recursive: true, force: true });
  await fs.mkdir(outDir, { recursive: true });

  const faces = [
    "/* Generated by scripts/build-fonts.js. Do not edit. */",
    "/* IBM Plex is licensed under the SIL Open Font License 1.1. */",
    ""
  ];
  let copied = 0;

  for (const font of FAMILIES) {
    const filesDir = path.join(path.dirname(require.resolve(`${font.package}/package.json`)), "files");

    for (const weight of font.weights) {
      const name = `${font.slug}-latin-${weight}-normal.woff2`;
      await fs.copyFile(path.join(filesDir, name), path.join(outDir, name));
      copied += 1;

      faces.push(
        `@font-face {`,
        `  font-family: '${font.family}';`,
        `  font-style: normal;`,
        `  font-weight: ${weight};`,
        `  font-display: swap;`,
        `  src: url('/fonts/${name}') format('woff2');`,
        `}`,
        ""
      );
    }
  }

  await fs.writeFile(path.join(outDir, "fonts.css"), faces.join("\n"), "utf8");
  console.log(`Copied ${copied} woff2 files and generated fonts.css -> ${outDir}`);
}

main().catch((error) => {
  console.error("\nFont build failed.\n");
  console.error(error.message);
  process.exit(1);
});
